// Interface automatically generated by schemas-to-ts

export interface Test {
	id: number;
	attributes: {
		createdAt: Date;
		updatedAt: Date;
		publishedAt?: Date;
		name?: string;
		isTest?: boolean;
		JSON?: any;
	};
}
export interface Test_Plain {
	id: number;
	createdAt: Date;
	updatedAt: Date;
	publishedAt?: Date;
	name?: string;
	isTest?: boolean;
	JSON?: any;
}

export interface Test_NoRelations {
	id: number;
	createdAt: Date;
	updatedAt: Date;
	publishedAt?: Date;
	name?: string;
	isTest?: boolean;
	JSON?: any;
}

export interface Test_AdminPanelLifeCycle {
	id: number;
	createdAt: Date;
	updatedAt: Date;
	publishedAt?: Date;
	name?: string;
	isTest?: boolean;
	JSON?: any;
}
