import type { Metadata } from 'next';
import './styles/layout.sass';
import { Layout } from '@/components';
import { SessionProvider } from 'next-auth/react';

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="ru">
			<body>
				<SessionProvider>
					<Layout>{children}</Layout>
				</SessionProvider>
			</body>
		</html>
	);
}
