// Interface automatically generated by schemas-to-ts

import { Media } from '../common/Media';
import { Media_Plain } from '../common/Media';
import { AdminPanelRelationPropertyModification } from '../common/AdminPanelRelationPropertyModification';

export interface Article {
	id: number;
	attributes: {
		createdAt: Date;
		updatedAt: Date;
		publishedAt?: Date;
		title: string;
		content?: any;
		image: { data: Media };
		slug: string;
	};
}
export interface Article_Plain {
	id: number;
	createdAt: Date;
	updatedAt: Date;
	publishedAt?: Date;
	title: string;
	content?: any;
	image: Media_Plain;
	slug: string;
}

export interface Article_NoRelations {
	id: number;
	createdAt: Date;
	updatedAt: Date;
	publishedAt?: Date;
	title: string;
	content?: any;
	image: number;
	slug: string;
}

export interface Article_AdminPanelLifeCycle {
	id: number;
	createdAt: Date;
	updatedAt: Date;
	publishedAt?: Date;
	title: string;
	content?: any;
	image: AdminPanelRelationPropertyModification<Media_Plain>;
	slug: string;
}
