// Interface automatically generated by schemas-to-ts

import { Video } from './video';
import { Course } from './course';
import { Material } from './material';
import { Video_Plain } from './video';
import { Course_Plain } from './course';
import { Material_Plain } from './material';
import { AdminPanelRelationPropertyModification } from '../common/AdminPanelRelationPropertyModification';

export interface CourseContent {
	id: number;
	attributes: {
		createdAt: Date;
		updatedAt: Date;
		publishedAt?: Date;
		title: string;
		videos: { data: Video[] };
		name: string;
		course?: { data: Course };
		materials: { data: Material[] };
	};
}
export interface CourseContent_Plain {
	id: number;
	createdAt: Date;
	updatedAt: Date;
	publishedAt?: Date;
	title: string;
	videos: Video_Plain[];
	name: string;
	course?: Course_Plain;
	materials: Material_Plain[];
}

export interface CourseContent_NoRelations {
	id: number;
	createdAt: Date;
	updatedAt: Date;
	publishedAt?: Date;
	title: string;
	videos: number[];
	name: string;
	course?: number;
	materials: number[];
}

export interface CourseContent_AdminPanelLifeCycle {
	id: number;
	createdAt: Date;
	updatedAt: Date;
	publishedAt?: Date;
	title: string;
	videos: AdminPanelRelationPropertyModification<Video_Plain>;
	name: string;
	course?: AdminPanelRelationPropertyModification<Course_Plain>;
	materials: AdminPanelRelationPropertyModification<Material_Plain>;
}
