// Interface automatically generated by schemas-to-ts

import { CourseContent } from './course-content';
import { CourseContent_Plain } from './course-content';
import { AdminPanelRelationPropertyModification } from '../common/AdminPanelRelationPropertyModification';

export interface Course {
	id: number;
	attributes: {
		createdAt: Date;
		updatedAt: Date;
		publishedAt?: Date;
		title?: string;
		src_telegram_bot?: string;
		token_puzzle_bot?: string;
		section: string;
		course_contents: { data: CourseContent[] };
	};
}
export interface Course_Plain {
	id: number;
	createdAt: Date;
	updatedAt: Date;
	publishedAt?: Date;
	title?: string;
	src_telegram_bot?: string;
	token_puzzle_bot?: string;
	section: string;
	course_contents: CourseContent_Plain[];
}

export interface Course_NoRelations {
	id: number;
	createdAt: Date;
	updatedAt: Date;
	publishedAt?: Date;
	title?: string;
	src_telegram_bot?: string;
	token_puzzle_bot?: string;
	section: string;
	course_contents: number[];
}

export interface Course_AdminPanelLifeCycle {
	id: number;
	createdAt: Date;
	updatedAt: Date;
	publishedAt?: Date;
	title?: string;
	src_telegram_bot?: string;
	token_puzzle_bot?: string;
	section: string;
	course_contents: AdminPanelRelationPropertyModification<CourseContent_Plain>;
}
