// Interface automatically generated by schemas-to-ts

import { CourseContent } from './course-content';
import { CourseContent_Plain } from './course-content';
import { AdminPanelRelationPropertyModification } from '../common/AdminPanelRelationPropertyModification';

export interface Material {
	id: number;
	attributes: {
		createdAt: Date;
		updatedAt: Date;
		publishedAt?: Date;
		title?: string;
		src?: string;
		course_content?: { data: CourseContent };
	};
}
export interface Material_Plain {
	id: number;
	createdAt: Date;
	updatedAt: Date;
	publishedAt?: Date;
	title?: string;
	src?: string;
	course_content?: CourseContent_Plain;
}

export interface Material_NoRelations {
	id: number;
	createdAt: Date;
	updatedAt: Date;
	publishedAt?: Date;
	title?: string;
	src?: string;
	course_content?: number;
}

export interface Material_AdminPanelLifeCycle {
	id: number;
	createdAt: Date;
	updatedAt: Date;
	publishedAt?: Date;
	title?: string;
	src?: string;
	course_content?: AdminPanelRelationPropertyModification<CourseContent_Plain>;
}
