// Interface automatically generated by schemas-to-ts

import { Video } from './video';
import { Video_Plain } from './video';
import { AdminPanelRelationPropertyModification } from '../common/AdminPanelRelationPropertyModification';

export interface VideoTimestamp {
	id: number;
	attributes: {
		createdAt: Date;
		updatedAt: Date;
		publishedAt?: Date;
		title?: string;
		second?: number;
		video?: { data: Video };
	};
}
export interface VideoTimestamp_Plain {
	id: number;
	createdAt: Date;
	updatedAt: Date;
	publishedAt?: Date;
	title?: string;
	second?: number;
	video?: Video_Plain;
}

export interface VideoTimestamp_NoRelations {
	id: number;
	createdAt: Date;
	updatedAt: Date;
	publishedAt?: Date;
	title?: string;
	second?: number;
	video?: number;
}

export interface VideoTimestamp_AdminPanelLifeCycle {
	id: number;
	createdAt: Date;
	updatedAt: Date;
	publishedAt?: Date;
	title?: string;
	second?: number;
	video?: AdminPanelRelationPropertyModification<Video_Plain>;
}
